FROM python:3.13-slim

# Set environment variables & uv configuration
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV UV_PROJECT_ENVIRONMENT=/usr/local
ENV UV_LINK_MODE=copy

# Installing uv from Astral's uv image
COPY --from=ghcr.io/astral-sh/uv:0.5.1 /uv /uvx /bin/

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen --no-cache --group dev --no-install-project